#ifndef REQUESTSCONSTANTS_H
#define REQUESTSCONSTANTS_H

#define STATUS_OK                   200
#define STATUS_BAD_REQUEST          400
#define STATUS_USER_NOT_ID          401
#define STATUS_UNAUTHORIZED         403
#define STATUS_DELETE_REJECTED      405
#define STATUS_INCORRECT_PLACEMENT  409
#define STATUS_SONG_REJECTED        413
#define STATUS_INCORRECT_FORMAT     415
#define STATUS_SERVER_ERROR         500 

#define SECURE_CONNECTION_PORT      "443"

#endif
